name: Send Gmail Notification
on:
#  push:
#   branches: [ ]
  workflow_dispatch:
jobs:  
  Send_Email_Notification:
    runs-on: self-hosted
    steps:

      - name: 'Git Version'
        run: git --version

      - name: 'Git Checkout'  
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Check for File availability
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "date.txt"

      # - name: Send mail with Attachment
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # mail server settings
      #     server_address: smtp.gmail.com
      #     server_port: 587

      #     # user credentials
      #     # username: ${{ secrets.EMAIL_USERNAME }}
      #     # password: ${{ secrets.EMAIL_PASSWORD }}
          
      #     username: mohankrishnapsl@gmail.com
      #     password: ${{ secrets.EMAIL_PASSWORD }}

      #     # email subject
      #     subject: 'Testing email using GitHub Actions'

      #     #attachments
      #     attachments: date.txt
          
      #     # email body as text
      #     body: 'Sending email via Github Actions. Email via Github actions is working!!! Hurrah!!'
          
      #     # comma-separated string, send email to
      #     to: mohankrishnapsl@gmail.com
          
      #     # from email name
      #     from: Mohan Krishna

      # - name: Send mail without Attachment
      #   if: steps.check_files.outputs.files_exists == 'false'
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # mail server settings
      #     server_address: smtp.gmail.com
      #     server_port: 587

      #     # user credentials
      #     # username: ${{ secrets.EMAIL_USERNAME }}
      #     # password: ${{ secrets.EMAIL_PASSWORD }}
          
      #     username: mohankrishnapsl@gmail.com
      #     password: ${{ secrets.EMAIL_PASSWORD }}

      #     # email subject
      #     subject: 'Testing email using GitHub Actions'

      #     #attachments
      #     # attachments: date.txt
          
      #     # email body as text
      #     body: 'Sending email via Github Actions. Email via Github actions is working!!! Hurrah!!'
          
      #     # comma-separated string, send email to
      #     to: mohankrishnapsl@gmail.com
          
      #     # from email name
      #     from: Mohan Krishna
      
      - name: Send mail
        # env:
        #   ATTACHMENT : ${{ steps.check_files.outputs.files_exists == 'true' && 'date.txt' || ''}}
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 587

          # user credentials
          # username: ${{ secrets.EMAIL_USERNAME }}
          # password: ${{ secrets.EMAIL_PASSWORD }}
          
          username: mohankrishnapsl@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}

          # email subject
          subject: 'Testing email using GitHub Actions'

          #attachments
          attachments: ${{ steps.check_files.outputs.files_exists == 'true' && 'date.txt' || ''}}
          
          # email body as text
          body: Github Repository - ${{github.repository}} $Sending email via Github Actions. Email via Github actions is working!!! Hurrah!!
          
          # comma-separated string, send email to
          to: mohankrishnapsl@gmail.com, kannayya01@gmail.com
          
          # from email name
          from: Mohan Krishna
