name: Send Email Notification
on:
#  push:
#   branches: [ ]
  workflow_dispatch:
jobs:  
  Send_Email_Notification:
    runs-on: self-hosted
    steps:
      - name: create a date.txt file
        run: echo "June 8th 2023" > date.txt

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "date.txt"

      # - name: File exists
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   run: echo "It exists !"

      - name: Send mail with Attachment
        if: steps.check_files.outputs.files_exists == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 587

          # user credentials
          # username: ${{ secrets.EMAIL_USERNAME }}
          # password: ${{ secrets.EMAIL_PASSWORD }}
          
          username: mohankrishnapsl@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}

          # email subject
          subject: 'Testing email using GitHub Actions'

          #attachments
          attachments: date.txt
          
          # email body as text
          body: 'Sending email via Github Actions. Email via Github actions is working!!! Hurrah!!'
          
          # comma-separated string, send email to
          to: mohankrishnapsl@gmail.com
          
          # from email name
          from: Mohan Krishna
       